# \u914D\u7F6E HTTPS \u76F8\u5173\u4FE1\u606F
server:
  port: 443
  # \u4E3A\u4E86\u540E\u9762\u7684\u914D\u7F6E\u4F7F\u7528,\u6682\u65F6\u65E0\u7528
  http-port: 80
  ssl:
    enabled: true
    # \u8BC1\u4E66\u6587\u4EF6
    key-store: classpath:springboot_https.keystore
    # \u5BC6\u7801
    key-password: 123456
    # \u5BC6\u94A5\u5E93\u7C7B\u578B
    key-store-type: JKS
    key-alias: springboot_https
