# 项目服务器的根路径
server:
  servlet:
    context-path: /web

spring:
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      # 数据源1 mysql
      mysql:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
        username: root
        password: root
        # 连接池的配置
        initial-size: 5
        min-idle: 5
        max-active: 20
        # 连接等待超时时间
        max-wait: 30000
        # 配置检测可以关闭的空闲连接间隔时间
        time-between-eviction-runs-millis: 60000
        # 配置连接在池中的最小生存时间
        min-evictable-idle-time-millis: 300000
        validation-query: select '1' from dual
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        # 打开PSCache,并且指定每个连接上的PSCache的大小
        pool-prepared-statements: true
        max-open-prepared-statements: 20
        max-pool-prepared-statement-per-connection-size: 20
      # 数据源2 oracle
      oracle:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521:orcl
        username: scott
        password: tigger
        # 连接池的配置
        initial-size: 5
        min-idle: 5
        max-active: 20
        # 连接等待超时时间
        max-wait: 30000
        # 配置检测可以关闭的空闲连接间隔时间
        time-between-eviction-runs-millis: 60000
        # 配置连接在池中的最小生存时间
        min-evictable-idle-time-millis: 300000
        validation-query: select '1' from dual
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        # 打开PSCache,并且指定每个连接上的PSCache的大小
        pool-prepared-statements: true
        max-open-prepared-statements: 20
        max-pool-prepared-statement-per-connection-size: 20

      # 配置监控统计拦截的filters,去掉后监控界面的sql无法统计,'wall'用于防火墙
      filters: stat,wall
      # Spring监控的AOP切入点,如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.springboot.service.*

      #WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      #StatViewFilter配置
      stat-view-servlet:
        enabled: true
        #设置进入Druid监控界面的请求
        url-pattern: /druid/*
        #是否能够重置数据
        reset-enable: false
        #设置访问Druid控制台的账户和密码
        #login-username: admin
        #login-password: admin
        # IP白名单
        # allow: 127.0.0.1
        #　IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218
      #配置StatFilter
      filter:
        stat:
          log-slow-sql: true
        wall:
          config:
            multi-statement-allow: true
#配置类中已经关联过xml
#mybatis:
  # type-aliases扫描路径
  # type-aliases-package:
  # mapper xml实现扫描路径
  #mapper-locations: classpath:mapper/*.xml