spring:
  rabbitmq:
    #RabbitMQ的用户名,默认为guest
    username: guest
    #RabbitMQ的密码,默认为guest
    password: guest
    addresses: localhost:5672
    cache:
      connection:
        #缓存连接模式,默认一个连接,多个channel
        mode: channel
        #多个连接,多个channel
        #mode: connection